### ISSUE TITLE
Options Menu disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [cbeyls/fosdem-companion-android#19]
When i perform this sequence of events, the menu disappears:

1. Open Side Drawer
2. Click on Bookmarks
3. Click on Sort icon
4. Orientation Change

**Comment by cbeyls** [comment]
AppCompat does not keep track of which sub-menu items are expanded or collapsed and this state is loss after orientation change because menu items are re-created. To my knowledge, there is no way of manually retrieving a sub-menu expanded state or programmatically expanding a sub-menu so this behavior cannot be changed. I've seen it in other apps too. You may file a feature request on the official Android bug tracker.
