### ISSUE TITLE
Actionbar back from Live event opens track view

### ISSUE THREAD

**Issue by Qinusty** [cbeyls/fosdem-companion-android#33]
When attempting to navigate back to the live events view, pressing the back button on the actionbar takes you to the track which the event is from.

**Comment by cbeyls** [comment]
This is actually a feature and the expected behavior of the [up button](https://developer.android.com/design/patterns/navigation.html) which is different from the back button even if they do the same thing most of the time.

The rules are:
- The up button must never navigate the user out of the app
- The up button must navigate to the upper level of the app
- There is no up button when you reach the top of the app.

When the details screen is opened from a notification for example, the up button on that screen allows to reach the main menu of the app from there.
Also, when opening a talk from bookmarks, speakers details or the live view, the up button allows reaching the track of this talk so you can see the next and previous talks in that room.
