### ISSUE TITLE
App crash when text is selected

### ISSUE THREAD

**Issue by flowolf** [cbeyls/fosdem-companion-android#38]
We noticed a rare bug. The app crashes when text is selected and one switches between talks with a swipe.

the bugreport [here](https://github.com/linuxtage/glt-companion/issues/8) includes a video. I was able to crash the app on Android 8.0.0 as well.

**Comment by cbeyls** [comment]
Thanks for the report. I noticed the same bug this year and didn't change anything specific in the layouts so I assume this is a bug in Android Oreo. Not sure how I can prevent it without disabling copy paste entirely.

**Comment by cbeyls** [comment]
It may be related to the support library then... I'll investigate again when I have time.

**Comment by cbeyls** [comment]
I went to the bottom of this issue and identified [the cause](https://stackoverflow.com/questions/15836306/can-a-textview-be-selectable-and-contain-links).
It turns out that text selection is using `ArrowKeyMovementMethod` internally, while in code I was additionally setting up a `LinkMovementMethod` in order to make links clickable. These two don't play well together.

To fix this I'll have to either:
- Disable text selection
- Disable clickable links
- Implement a custom `MovementMethod` which handles both properly.

I'm investigating the last one.
