### ISSUE TITLE
Adding Kotlin code in the repo

### ISSUE THREAD

**Issue by cortinico** [cbeyls/fosdem-companion-android#39]
Hey @cbeyls 
I checked the codebase and is only Java.

I wanted to convert some classes to Kotlin, are you ok with that?
Or are there any reason why this repo should be Java only?

**Comment by cbeyls** [comment]
Hello, indeed the project is Java-only for now. Since it's been forked a few times, I don't want the maintainers to be forced to use a new language. I would rather have the project entirely rewritten to Kotlin at some point, in a different repo. I don't see the urge to convert some classes to Kotlin and add a dependency to the Kotlin stdlib for a perfectly working Java project :)

**Comment by cortinico** [comment]
Yup I see your point 👍
