### ISSUE TITLE
Show clashes in bookmarks view

### ISSUE THREAD

**Issue by wjt** [cbeyls/fosdem-companion-android#4]
I have bookmarked both Bron Gondwana's JMAP lightning talk and Daniel Lobato's Foreman talk. They are both at 11am on Sunday, but there's no indication in the app that they clash.

Many years ago someone contributed this feature to [my equivalent app for the N900](http://willthompson.co.uk/sojourner/) so maybe I should pay it forward …

**Comment by cbeyls** [comment]
Thanks for the suggestion, I'll look at how to implement this... but It'll probably be for next year.

**Comment by cbeyls** [comment]
I looked at how it's implemented in you N900 app and it's actually comparing each bookmark to every other one, in-memory. It's kind of heavy because it's in-memory it's acceptable. But this app reads bookmarks from a Database cursor so there's no way I perform a query for each bookmark, it would be way too slow. If you have a suggestion on how to implement this efficiently, feel free to share it.

**Comment by wjt** [comment]
I don't expect a subquery like in the patch above to be slow: the number of bookmarks is (expected to be) small in any case… This would give you the existence of a clash for a bookmark; the event detail view could perform a similar query to list the clashes.
