### ISSUE TITLE
Make the room name a link in the talk view (same way the building is a link)

### ISSUE THREAD

**Issue by tasn** [cbeyls/fosdem-companion-android#45]
If you open a talk view from the room list, there's no problem, you can just hit "back" and you'll be back in the room list. Though if you're coming from anywhere else, for example, from your bookmarks or clicking on the notifiction. You can't easily jump to the dev room of the talk you're currently viewing. You'd have to jump through hoops to get there which is quite annoying.

I guess it will also solve #34

Thanks a lot for fosdem companion!

**Comment by cbeyls** [comment]
Pressing the up button (at the top of the screen) instead of the back button will get you to the track list.

**Comment by tasn** [comment]
That's very confusing, but useful to know. Solves my usecase, so I'm happy. :P 
Though I think it should still be a link, no?

**Comment by cbeyls** [comment]
Indeed the "up" button is confusing for a lot of people, especially because many apps don't implement it properly despite all the guidelines provided by Google.
Links open a new screen in order to navigate forward, so you can press the back button to go back to the screen containing the link.
The "up" button closes the current screen and navigates back to the parent screen, in this case the track screen. This is a different behavior. I believe this is the correct navigation pattern in this case, because the track screen is semantically the parent screen of the current talk, each talk belonging to a single track.

**Comment by tasn** [comment]
Sounds reasonable. :)
