### ISSUE TITLE
Auto-scroll to current time in Bookmarks view

### ISSUE THREAD

**Issue by keunes** [cbeyls/fosdem-companion-android#46]
I'm always bookmarking too many talks (guess FOSDEM is interesting) and relying on my Bookmarks overview to see where I could go next (depending also on room availability). However, every time I move away from the bookmarks view to read more about the talk, the position of the bookmarks view is lost. It would help if the position is remembered and it would be cool if it auto-scrolls to the current time (so that after an hour-long talk I have an immediate overview of where I can go next, without scrolling).

Thanks for the handy app!

**Comment by keunes** [comment]
Thinking just now that maybe instead a gilter or tab in tje 'live' screen might be a better solution.

**Comment by cbeyls** [comment]
If you press the back button (at the bottom) instead of the up button (at the top), scroll position is always restored to where it was when you left the screen.

Also there is a filter option on the bookmarks screen, "upcoming only", where the next talk is always shown at the top of the screen and others are hidden. This view is updated in real time so 5 minutes after a talk starts, it's removed from the list.

**Comment by keunes** [comment]
hah, perfect. I missed the filtering option :+1:
