### ISSUE TITLE
Import bookmarks

### ISSUE THREAD

**Issue by sim6** [cbeyls/fosdem-companion-android#52]
Firstly, thanks for your work.

Could you add support to import the bookmarks exportation (ics)?

Thanks.

**Comment by cbeyls** [comment]
That would be a big feature, I wont have time to do it for FOSDEM 2020.
For now you can use NFC to transfer bookmarks from one Android device to another (they both need an NFC Chip with Android Beam enabled).

**Comment by sim6** [comment]
No problem, maybe for the next FOSDEM ;-)

**Comment by cbeyls** [comment]
Now that Android Beam is officially deprecated, this feature is at the top of my priorities.

First thoughts about the implementation details:
- considering using the [storage access framework](https://developer.android.com/guide/topics/providers/document-provider) available since API 19 to allow the user to pick files of MIME type `text/calendar` using a picker provided by the system. Either bump the app minSDKVersion to 19 now or don't provide the feature on API 17-18 devices
- the app would use an optimized parser for iCalendar format, doing basic sanity checks and allowing to skip unneeded data using a simple API
- the id of the talk would be extracted from the UID of each iCalendar event. The UID format is currently **id**@**year**@**application_id**
- the app validates that year and application id are matching the current database year and application id, or show an error message.
