### ISSUE TITLE
Notifications are making noise even at "do not disturb" mode

### ISSUE THREAD

**Issue by leon-anavi** [cbeyls/fosdem-companion-android#53]
Hi,

Great app! I enjoy using it but if the notifications are turned on, the app plays sound alarm even in "do not disturb" mode. I think this is a bug, is it?

Thanks, Leon

**Comment by cbeyls** [comment]
Hello,
It may be a bug with your device. My phone is on silent mode all day long and the notifications of the app don't play sound or make the phone vibrate.
Can you tell me which version of Android you are running?

**Comment by leon-anavi** [comment]
Thanks for the quick feedback. I am with Xiaomi A3 Android One phone with Android 9. Here are the details:

![Screenshot_20200202-162318](https://user-images.githubusercontent.com/3279083/73610515-7b2caf80-45d8-11ea-9941-1723329b5b5b.png)

Best regards, Leon

**Comment by cbeyls** [comment]
Thank you for the details.
Starting with Android 8.0, the vibration and sound of the notifications are not controlled by the app itself, instead the app can only provide default settings when installing then app but then the actual sound and vibration that will be used are enforced by the OS, in order to follow the settings of the notifications channel. So there is nothing the app can do about it.
Check out the notification channel settings of the app on your phone and make sure you did not check the box "ignore do not disturb mode".
