### ISSUE TITLE
Use geo URI in MapFragment.java

### ISSUE THREAD

**Issue by bparmentier** [cbeyls/fosdem-companion-android#6]
Why not use a geo URI instead of a Google Maps link in [MapFragment.java](https://github.com/cbeyls/fosdem-companion-android/blob/master/app/src/main/java/be/digitalia/fosdem/fragments/MapFragment.java#L53)?

On my device the link is handled by OsmAnd (at least it is proposed in the list of applications when tapping the Directions button). I guess they intercept the `maps.google.com` link on their side, but that could not be the case for all navigation apps.

**Comment by cbeyls** [comment]
The advantages of the Google http URL are:
1) It can be opened by a browser when no dedicated app is installed.
2) With the Google maps Uri scheme it's possible to pass parameters to launch directions using public transports, while the geo Uri only allows to center the map around a location.

Geo Uri could be used as a fallback mechanism for that scenario but because there is always a browser installed there is no need for a fallback.

The alternative would be to test if an app responds to a Geo Uri, and if none does then open an Http Uri to an open street maps web site or similar. This would work but people wanting the best integration with the Google Maps app would be penalized so I'm still hesitant to implement this because apps like OsmAnd are also compatible with the Google Maps Uri scheme.
