### ISSUE TITLE
Improve Navigation on Bookmarks page

### ISSUE THREAD

**Issue by richardeigenmann** [cbeyls/fosdem-companion-android#7]
Thanks for this helpful app and your talk about it in the Lightning Talks.
I think there was an unfortunate choice in the navigation on the Bookmarks page. When you decide that you want to uncheck a bookmarked session and then click the back button you are taken to the tracks list instead of the bookmarks list.

**Comment by cbeyls** [comment]
Hello,

When you are on the details page, the arrow at the top is an "up" button and not a back button. The "up" button brings you back to the track of the currently viewed session. If you want to go back instead of up, use the Android back button instead. You can find more information about "up" vs "back" navigation on that page: http://developer.android.com/design/patterns/navigation.html

Also note that you can delete bookmarks in bulk by long-pressing a bookmark in the bookmarks list to start the multi-selection mode on Android 3+.

**Comment by richardeigenmann** [comment]
Thanks for the link to the interesting article. I guess I didn't get the difference between back and up.

However, I do feel that the user experience was confusing. As the article points out sometimes back and up do exactly the same thing. If I open the app and go straight to the bookmarks, open an item and then click on an arrow that looks like a back arrow (even though it is an up arrow) I do maintain that it is confusing that the button should take me to the track listing which I have not seen before in the session. I expected to be taken back. Going to the track it fine, but from an icon or menu that makes this more intuitive for me.

Obviously I didn't self discover the multi-select and delete in the bookmarks page. It would have been helpful. What I found odd was that pressing on the bookmark in the bookmark listings doesn't do anything. Perhaps you could make it so that a tap on the bookmark icon on the right triggers the multi-select immediately instead of waiting for the long press?

**Comment by cbeyls** [comment]
Regarding the "up" navigation mode, the proper way to implement up navigation is described in the developer documentation, mainly [here](http://developer.android.com/training/implementing-navigation/ancestral.html). They explain that you need to provide a parent activity for your activity (in case of a session, the parent is the track), and then that the built-in default implementation will pop all the activities of the stack up to the parent activity if it's currently in the stack of the current task. If it's not, it will finish the current activity and launch a new instance of the parent activity. That's the exact behaviour you can observe in this app, and I see no other way to implement it, except from removing the "up" feature completely. I find this feature useful because it allows the user to see the sessions coming before and after to the one (s)he's currently viewing.
I agree that "Up" navigation is a difficult subject because few apps implement it properly, and as such many users are confused by it when it works as it should. The main thing to keep in mind is that when you want to navigate back in time, you should always use the Android back button at the bottom of the screen, and the up arrow can be used when you want to move up in the logical hierarchy of the app.

Long-pressing items on a list is actually a common pattern on Android; I'm not reinventing the wheel here but reusing a dedicated mode of the ListView (CHOICE_MODE_MULTIPLE_MODAL) which automatically launches a contextual action bar when long-pressing an item. You can find more information about this pattern [here](http://developer.android.com/design/patterns/selection.html) (section: "Using the contextual action bar").

**Comment by richardeigenmann** [comment]
I can see why I am confused: The recommended app behaviours have evolved since I got my first Android 1.5 device and the app universe has implemented their UIs under whatever design was prevalent at the time so my user experience (and expectation) is all over the shop.

I agree that the up navigation is really useful and actually it was something I missed. I just didn't expect the arrow pointing left to be one that takes me to a track listing. Now I feel silly.

I think the thing which didn't help me get the long-press selection is that the short-press opens the item. And I wasn't expecting a multi select option in the first place. My Bad.
You could make a short press on just the bookmark icon trigger the multi select CAB. I don't think a user would expect the detail to open when tapping the bookmark icon vs. the rest of the row.

**Comment by cbeyls** [comment]
How do you suggest to change it?
